backend/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  get  '/contact',      to: 'static_pages#contact',      as: 'contact'
  post '/contact_post', to: 'static_pages#contact_post', as: 'contact_post'

  get    '/signup', to: 'users#new', as: 'new_user'
  get    '/login', to: 'sessions#new', as: 'new_session'
  delete '/logout', to: 'sessions#destroy', as: 'session'

  get '/auth/:provider/callback', to: 'providers#create', as: 'provider_callback'
  get '/auth/failure', to: 'providers#failure', as: 'provider_failure'

  scope :settings do
    get '/user', to: 'users#edit', as: 'edit_user'
    get '/profile', to: 'profiles#edit', as: 'edit_user_profile'
  end

  resources :users, except: %i[new], param: :name do
    resources :profiles, only: %i[update]

    get '/microposts', to: 'users#microposts'
    get '/followers',  to: 'users#followers'
    get '/following',  to: 'users#following'
  end

  resources :sessions, only: %i[create]
  resources :account_activations, only: %i[new create edit], path: :confirms
  resources :password_resets, only: %i[new create edit update], path: :passwords
  resources :microposts do
    resources :comments, only: %i[create update destroy]
  end
  resources :relationships, only: %i[create destroy]
end

backend/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  has_rich_text :content

  validates :title, presence: true, length: { maximum: 128 }
  validates :content, presence: true, length: { maximum: 10000 }
end

backend/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # user authentication
  before_action :logged_in_user, only: %i[new create edit update destroy]
  before_action :activate_user, only: %i[new create edit update destroy]
  before_action :set_micropost
  before_action -> { correct_micropost_user(@micropost) }, only: %i[edit update destroy]

  def index
  end

  def new
  end

  def create
    respond_to do |format|
      if @micropost.save
        flash[:notice] = t('.micropost_was_created')
        format.html { redirect_to micropost_path(@micropost) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        flash[:notice] = t('.micropost_was_updated')
        format.html { redirect_to micropost_path(@micropost) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
      end
    end
  end

  def destroy
    @micropost.destroy
    flash[:notice] = t('.micropost_was_deleted')
    redirect_to root_path(), status: :see_other
  end

  private

  def micropost_params
    params.require(:micropost).permit(:title, :content)
  end

  def set_micropost
    case action_name
    when 'index'   then @microposts = Micropost.eager_load(:user).all.with_rich_text_content
    when 'new'     then @micropost  = current_user.microposts.new()
    when 'create'  then @micropost  = current_user.microposts.new(micropost_params)
    when 'show'    then @micropost  = Micropost.eager_load(:user, comments: { user: { profile: { avatar_attachment: :blob }}}).with_rich_text_content.find(params[:id])
    when 'edit'    then @micropost  = Micropost.eager_load(:user).find(params[:id])
    when 'update'  then @micropost  = Micropost.with_rich_text_content.find(params[:id])
    when 'destroy' then @micropost  = Micropost.eager_load(:user).with_rich_text_content.find(params[:id])
    end
  end

  def correct_micropost_user(micropost)
    unless current_user?(micropost.user)
      flash[:alert] = t('you_are_not_current_user')
      redirect_to(root_url(), status: :see_other)
    end
  end
end

backend/app/helpers/microposts_helper.rb
module MicropostsHelper
  def micropost_form_field(form, field, text, options = {})
    send = get_micropost_form_field_name(field)
    options[:class] = "w-full text-md #{options[:class]}"

    content_tag(:div) do
      form.label(text) +
      form.send(send, field, options)
    end
  end

  def micropost_form_submit(form, text, options = {})
    options[:class] = "text-sm p-2 bg-emerald-500 border border-gray-500 rounded shadow text-white hover:bg-emerald-400 #{options[:class]}"

    form.submit(text, options)
  end

  private

  def get_micropost_form_field_name(field)
    case field
    when :title   then 'text_field'
    when :content then 'rich_text_area'
    end
  end
end

backend/app/views/microposts/_edit_form.html.erb
<%= form_with model: @micropost, method: :patch do |f| %>
  <div class="space-y-4">
    <%= render 'shared/form_errors', object: f.object %>
    <%= micropost_form_field(f, :title,   t('.title')) %>
    <%= micropost_form_field(f, :content, t('.content')) %>
    <%= micropost_form_submit(f, t('.update_micropost')) %>
  <div>
<% end %>

backend/app/views/microposts/_micropost.html.erb
<div class="w-full p-4">
  <div class="p-4 bg-white border border-gray-200">
    <div class="flex flex-col overflow-hidden">
      <div class="text-xs">
        <%= content_tag(:span, "#{t('.contributor')}: ") %>
        <%= link_to(micropost.user.name, user_path(micropost.user), class: 'truncate text-sky-500 hover:text-violet-500') %>
      </div>
      <div class="text-xl">
        <%= link_to(micropost.title, micropost_path(micropost), class: 'truncate text-black hover:text-violet-500') %>
      </div>
      <div class="text-sm text-gray-400">
        <%= content_tag(:div, strip_tags(micropost.content.to_s), class: 'truncate') %>
      </div>
      <div class="block md:flex md:flex-row md:items-center text-xs md:space-x-2">
        <div class="text-xs">
          <%= content_tag(:span, "#{t('.created_at')}: ") %>
          <%= content_tag(:div, micropost.created_at, class: 'truncate inline text-gray-400') %>
        </div>
        <div class="text-xs">
          <%= content_tag(:span, "#{t('.updated_at')}: ") %>
          <%= content_tag(:div, micropost.updated_at, class: 'truncate inline text-gray-400') %>
        </div>
      </div>
    </div>
  </div>
</div>

backend/app/views/microposts/_new_form.html.erb
<%= form_with model: @micropost, method: :post do |f| %>
  <div class="space-y-4">
    <%= render 'shared/form_errors', object: f.object %>
    <%= micropost_form_field(f, :title,   t('.title')) %>
    <%= micropost_form_field(f, :content, t('.content')) %>
    <%= micropost_form_submit(f, t('.create_micropost')) %>
  </div>
<% end %>

backend/app/views/microposts/edit.html.erb
<% provide(:title, t('.title')) %>

<div class="w-full p-4">
  <%= content_tag(:h1, t('.title'), class: 'text-center text-xl') %>
  <%= render 'edit_form' %>
</div>

backend/app/views/microposts/index.html.erb
<% provide(:title, t('.title')) %>

<%= content_tag(:h1, t('.title'), class: 'text-center pt-4 text-xl ') %>

<%= render @microposts %>

backend/app/views/microposts/new.html.erb
<% provide(:title, t('.title')) %>

<div class="w-full p-4">
  <%= content_tag(:h1, t('.title'), class: 'text-center text-xl') %>
  <%= render 'new_form' %>
</div>

backend/app/views/microposts/show.html.erb
<% provide(:title, t('.title')) %>

<div class="w-full p-4 bg-gray-200 space-y-4">
  <div class="bg-white rounded p-4 divide-y">
    <div class="py-2">
      <%= content_tag(:h1, @micropost.title, class: 'text-2xl font-bold text-left break-words') %>
      <div class="text-xs">
        <%= content_tag(:span, "#{t('.contributor')}: ") %>
        <%= link_to(@micropost.user.name, user_path(@micropost.user), class: 'truncate text-sky-500 hover:text-violet-500') %>
      </div>
      <div class="block md:flex md:flex-row md:items-center text-xs md:space-x-2">
        <div class="text-xs">
          <%= content_tag(:span, "#{t('.created_at')}: ") %>
          <%= content_tag(:div, @micropost.created_at, class: 'truncate inline text-gray-400') %>
        </div>
        <div class="text-xs">
          <%= content_tag(:span, "#{t('.updated_at')}: ") %>
          <%= content_tag(:div, @micropost.updated_at, class: 'truncate inline text-gray-400') %>
        </div>
      </div>
    </div>
    <div class="py-2">
      <%= @micropost.content %>
    </div>
  </div>

  <%= render 'comments/page' %>

  <% if current_user?(@micropost.user) %>
    <div class="flex flex-col bg-gray-800 rounded p-4">
      <%= link_to(t('.edit_micropost'), edit_micropost_path(@micropost), class: 'text-sky-500 hover:text-violet-500') %>
      <%= link_to(t('.delete_micropost'), @micropost, { class: 'text-sky-500 hover:text-rose-500', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } }) %>
    </div>
  <% end %>
</div>