backend/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  get  '/contact',      to: 'static_pages#contact',      as: 'contact'
  post '/contact_post', to: 'static_pages#contact_post', as: 'contact_post'

  get    '/signup', to: 'users#new', as: 'new_user'
  get    '/login', to: 'sessions#new', as: 'new_session'
  delete '/logout', to: 'sessions#destroy', as: 'session'

  get '/auth/:provider/callback', to: 'providers#create', as: 'provider_callback'
  get '/auth/failure', to: 'providers#failure', as: 'provider_failure'

  scope :settings do
    get '/user', to: 'users#edit', as: 'edit_user'
    get '/profile', to: 'profiles#edit', as: 'edit_user_profile'
  end

  resources :users, except: %i[new], param: :name do
    resources :profiles, only: %i[update]

    get '/microposts', to: 'users#microposts'
    get '/followers',  to: 'users#followers'
    get '/following',  to: 'users#following'
  end

  resources :sessions, only: %i[create]
  resources :account_activations, only: %i[new create edit], path: :confirms
  resources :password_resets, only: %i[new create edit update], path: :passwords
  resources :microposts do
    resources :comments, only: %i[create update destroy]
  end
  resources :relationships, only: %i[create destroy]
end

backend/app/views/layouts/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag(:div, id: name, class: 'w-full p-2 flex items-center border border-black', 'data-application-target': 'flashMessages') do %>
    <button type="button" data-action="click->application#flash_messages_close">
      <span class="sr-only">Close panel</span>
      <%= render 'modules/x' %>
    </button>
    <span class="mt-0.5 pl-2"><%= msg %></span>
  <% end %>
<% end %>

backend/app/views/layouts/_footer.html.erb
<div class="w-full text-sm bg-amber-300 border-t border-orange-500 p-4 space-y-4">
  <div class="bg-amber-400 rounded border-2 border-rose-500">
    <%= content_tag(:h2, t('.technologys'), class: 'text-lg text-center text-white py-2') %>
    <div class="p-4 text-center">
      <%= footer_technology_link_to(t('.source_code'), 'https://github.com/ittoku703/mizusirazu/') %>
      <%= footer_technology_link_to('Ruby on Rails',   'https://rubyonrails.org/') %>
      <%= footer_technology_link_to('Tailwindcss',     'https://tailwindcss.com/') %>
      <%= footer_technology_link_to('Wall Haven',      'https://wallhaven.cc/') %>
      <%= footer_technology_link_to('Twitter',         'https://twitter.com/') %>
      <%= footer_technology_link_to('Github',          'https://github.com/') %>
    </div>
  </div>

  <div class="text-center p-4 border border-violet-500 bg-amber-400 rounded">
    <%= link_to(t('.contact'),  contact_path()) %>
  </div>

  <div class="text-center p-4 border border-teal-500 bg-amber-400 rounded">
    <%= content_tag(:p, t('copy_right'), class: '') %>
  </div>
</div>

backend/app/views/layouts/_header.html.erb
<div class="w-full bg-amber-300 px-4 border-b border-orange-500">
  <div class="my-1 flex justify-between items-center">
    <%= site_logo %>

    <div>
      <%= content_tag(:h1, t('my_site')) %>
    </div>

    <div class="relative inline-block">
      <div>
        <button type="button" class="inline-flex justify-center w-full px-4 py-2 text-gray-500" data-action="click->application#headerUserToggle" data-application-target="userBtn">
          <%= logged_in? && current_user.profile.avatar.attached? ?
            image_tag(current_user.profile.avatar, class: 'w-10 h-10 rounded-full bg-white') :
            fa_icon('sitemap')
          %>
          <%= render 'modules/bottom_allow' %>
        </button>
      </div>
      <div class="hidden arrow-top z-10 absolute right-0 mt-2 w-48 rounded shadow bg-gray-100 border border-gray-800" data-application-target="userList" tabindex="-1">
        <div class="py-2 text-sm">
        <%= header_link_to(t('.user_list'),          users_path()) %>
        <%= header_link_to(t('.micropost_list'),     microposts_path()) %>
        <% if logged_in? %>
          <%= header_link_to(t('.your_page'),        user_path(current_user)) %>
          <%= header_link_to(t('.create_micropost'), new_micropost_path()) %>
          <%= header_link_to(t('.settings'),         edit_user_path()) %>
          <%= header_link_to(t('.log_out'),          session_path(), data: { turbo_method: :delete }) %>
        <% else %>
          <%= header_link_to(t('.confirms'),         new_account_activation_path()) %>
          <%= header_link_to(t('.forget_password'),  new_password_reset_path()) %>
          <%= header_link_to(t('.sign_up'),          new_user_path()) %>
          <%= header_link_to(t('.log_in'),           new_session_path()) %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

backend/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <div class="flex flex-col min-h-screen" data-controller="application" data-action="click->application#pageClick">
      <%= render 'layouts/header' %>

      <%= render 'layouts/flash_messages' %>

      <main class="grow">
        <%= yield %>
      </main>

      <%= render 'layouts/footer' %>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>