backend/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'users#index'

  get  '/contact',      to: 'static_pages#contact',      as: 'contact'
  post '/contact_post', to: 'static_pages#contact_post', as: 'contact_post'

  get    '/signup', to: 'users#new', as: 'new_user'
  get    '/login', to: 'sessions#new', as: 'new_session'
  delete '/logout', to: 'sessions#destroy', as: 'session'

  get '/auth/:provider/callback', to: 'providers#create', as: 'provider_callback'
  get '/auth/failure', to: 'providers#failure', as: 'provider_failure'

  scope :settings do
    get '/user', to: 'users#edit', as: 'edit_user'
    get '/profile', to: 'profiles#edit', as: 'edit_user_profile'
  end

  resources :users, except: %i[new], param: :name do
    resources :profiles, only: %i[update]

    get '/microposts', to: 'users#microposts'
    get '/followers',  to: 'users#followers'
    get '/following',  to: 'users#following'
  end

  resources :sessions, only: %i[create]
  resources :account_activations, only: %i[new create edit], path: :confirms
  resources :password_resets, only: %i[new create edit update], path: :passwords
  resources :microposts do
    resources :comments, only: %i[create update destroy]
  end
  resources :relationships, only: %i[create destroy]
end

backend/app/models/user.rb
class User < ApplicationRecord
  has_one :profile, dependent: :destroy
  has_one :provider, dependent: :destroy
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :followed_id, dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  attr_accessor :remember_token, :activation_token, :reset_token,
                :skip_create_profile_model

  before_save :downcase_email
  before_create -> { create_activation_digest_before_create() unless activated? }
  after_create ->  { create_profile_model() unless skip_create_profile_model }
  after_create ->  { send_account_activation_email() unless activated? }

  validates :name, presence: true
  validates :name,
    format: { with: /\A[a-z0-9_]+\z/, message: 'only alphabets, digits and underscore' },
    length: { maximum: 128 },
    uniqueness: true,
    allow_blank: true

  validates :email, presence: true
  validates :email,
    format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i },
    length: { maximum: 256 },
    uniqueness: true,
    allow_blank: true

  has_secure_password

  validates :password, presence: true, on: :create
  validates :password,
    length: { in: 4..256 },
    allow_blank: true

  # return Hash values of the passed string
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ?
      BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # return the random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # create user, profile, provider models with omniauth
  def User.create_from_omniauth(models_hash)
    # Do not create a default profile
    models_hash[:user][:skip_create_profile_model] = true

    user_model = models_hash[:user]
    profile_model = models_hash[:profile]
    provider_model = models_hash[:provider]

    user = create(user_model)
    user.create_profile(profile_model)
    user.create_provider(provider_model)
    return user
  end

  # remember user in database for permanent sessions
  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  # return true if the token passed matched digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # destroy the user's login information
  def forget
    update(remember_digest: nil)
  end

  # activate your account
  def activate
    update(activated: true, activated_at: Time.zone.now, activation_sent_at: nil)
  end

  # send user mailer account activation email
  def send_account_activation_email
    return if hammaring_protection(:activation_sent_at)
    create_digest(:activation)
    UserMailer.account_activation(self).deliver_now
    update(activated: false, activation_sent_at: Time.zone.now)
  end

  # send user password reset email
  def send_password_reset_email
    return if hammaring_protection(:reset_sent_at)
    create_digest(:reset)
    UserMailer.password_reset(self).deliver_now
    update(reset_sent_at: Time.zone.now)
  end

  # save digest in database for user control
  def create_digest(attribute)
    attribute_digest = "#{attribute}_digest".to_sym
    attribute_token  = "#{attribute}_token".to_sym
    self.send("#{attribute_token}=", User.new_token)
    update({ attribute_digest => User.digest(self.send(attribute_token)) })
  end

  #
  def User.all_sort(selection)
    case selection
    when 'name'  then all.order(name: :ASC)
    when 'email' then all.order(email: :ASC)
    when 'new'   then all.order(created_at: :DESC)
    when 'old'   then all.order(created_at: :ASC)
    else all
    end
  end

  # following other_user
  def follow(other_user)
    following << other_user
  end

  # unfollowing other_user
  def unfollow(other_user)
    active_relationships.find_by_followed_id(other_user.id).destroy()
  end

  # return true if other_user followed
  def following?(other_user)
    following.include?(other_user)
  end

  # OVERRIDE: changed params id to params name
  def to_param
    name
  end

  private
    # make the email all downcase before saving account
    def downcase_email
      email.downcase!
    end

    # create profile after creating user
    def create_profile_model
      create_profile
    end

    # activate digest in database for email confirm
    def create_activation_digest_before_create
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    # return if email sent twice a second
    def hammaring_protection(email_sent_at)
      self.send(email_sent_at) && self.send(email_sent_at) > 1.second.before
    end
end

backend/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # authenticate
  before_action :logged_in_user, only: %i[edit update destroy]
  before_action :activate_user,  only: %i[edit update]
  before_action :already_logged_in, only: %i[new create]
  # set parameters
  before_action :set_user
  before_action -> { correct_user(@user) }, only: %i[update destroy]

  # GET /users
  def index
  end

  # GET /signup
  def new
  end

  # POST /users
  def create
    respond_to do |format|
      if verify_recaptcha(model: @user, action: 'signup')
        if @user.save
          flash[:notice] = t('.user_was_created')
          format.html { redirect_to root_path() }
        else
          # nessally status: :unprocessable_entity
          format.html { render :new, status: :unprocessable_entity }
        end
      else
        # Score is below threshold, so user may be a bot
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/:name
  def show
  end

  # GET /settings/user
  def edit
  end

  # GET /users/:name
  def update
    prev_email = @user.email

    respond_to do |format|
      if @user.update(user_params)
        flash[:notice] = t('.user_was_updated')
        if prev_email != @user.email
          flash[:notice] += '. ' + t('.email_changed')
          @user.send_account_activation_email()
          format.html { redirect_to root_path() }
        end
        format.html { redirect_to edit_user_path() }
      else
        format.html { render :edit, status: :unprocessable_entity, location: @user.reload }
      end
    end
  end

  # DELETE /users/:name
  def destroy
    @user.destroy
    flash[:notice] = t('.user_was_deleted')
    redirect_to(root_path(), status: :see_other)
  end

  # GET /users/:name/microposts
  def microposts
  end

  # GET /users/:user_name/followers
  def followers
  end

  # GET /users/:user_name/following
  def following
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    case action_name
    when 'index'      then @users = User.all_sort(params[:sort])
    when 'new'        then @user  = User.new
    when 'create'     then @user  = User.new(user_params)
    when 'show'       then @user  = User.eager_load(:microposts, profile: { avatar_attachment: :blob }).find_by_name!(params[:name])
    when 'edit'       then @user  = current_user
    when 'update'     then @user  = User.find_by_name!(params[:name])
    when 'destroy'    then @user  = User.eager_load(:provider, :microposts, profile: { avatar_attachment: :blob }).find_by_name!(params[:name])
    when 'microposts' then @user  = User.eager_load(:microposts).find_by_name!(params[:user_name])
    when 'followers'  then @user  = User.eager_load(:passive_relationships).find_by_name!(params[:user_name])
    when 'following'  then @user  = User.eager_load(:active_relationships).find_by_name!(params[:user_name])
    end
  end
end

backend/app/helpers/users_helper.rb
module UsersHelper
  def user_form_field(form, field_name, span_text = '', options = {})
    send = get_user_form_field_name(field_name)

    content_tag(:div, class: 'w-full') do
      form.label("#{field_name}", class: 'w-full block') +
      form.send(send, field_name, class: 'w-full text-sm border border-gray-400 rounded shadow focus:ring-emerald-500 ') +
      content_tag(:span, span_text, class: 'text-xs text-gray-500')
    end
  end

  def user_form_submit(form, text, options = {})
    options[:class] = 'w-full py-2 bg-emerald-400 border border-gray-400 rounded shadow hover:bg-emerald-500 hover:text-white'

    form.submit(text, options)
  end

  def user_form_destroy_field(form, submit_text, description)
    content_tag(:div) do
      content_tag(:h1, submit_text, class: 'text-xl text-rose-500 pb-2 border-b border-gray-500 mb-4') +
      user_destroy_link(submit_text, @user, class: 'inline-block bg-rose-500 text-white hover:bg-red-500 hover:text-white px-2 py-1 rounded border border-black') +
      content_tag(:span, description, class: 'block text-xs text-gray-500 md:mt-1')
    end
  end

  def user_index_tag(user, attribute_name, options = {})
    text = user.send(attribute_name)
    options[:class] = "#{options[:class]} block truncate"

    if text.nil?
      text = 'is empty'
      options[:class] += ' text-gray-400'
    end

    if attribute_name == :name
      content_tag(:div, class: 'p-4') do
        content_tag(:span, "#{attribute_name}", class: 'text-amber-500') +
        link_to(text, user, options)
      end
    else
      content_tag(:div, class: 'p-4') do
        content_tag(:span, "#{attribute_name}", class: 'text-amber-500') +
        content_tag(:div, text, options)
      end
    end
  end

  def user_show_tag(object, attribute_name, options = {})
    options[:class] = "#{options[:class]} flex items-center pt-2 space-x-4 border-amber-500"

    if attribute_name == :avatar
      attribute_options = { class: 'w-12 h-12 rounded-full bg-white border border-gray-500'}
      attribute = object.send(attribute_name).attached? ?
        image_tag(object.avatar, attribute_options) :
        image_tag('image-not-found.png', attribute_options)
    else
      attribute_options = { class: 'text-gray-600'}
      attribute = content_tag(:p, object.send(attribute_name), attribute_options)
    end

    content_tag(:div, options) do
      attribute_icon(object, attribute_name) +
      attribute
    end
  end

  def user_destroy_link(text, user, options = {})
    options[:data] = { turbo_method: :delete, turbo_confirm: 'Are you sure?' }

    link_to(text, user, options)
  end

  private
    def attribute_icon(object, attribute_name)
      return fa_icon('id-card') if object.class == User && attribute_name == :name

      case attribute_name
      # user
      when :avatar then fa_icon('camera-retro')
      # profile
      when :name then fa_icon('pencil')
      when :bio  then fa_icon('pencil-square-o')
      when :location then fa_icon('location-arrow')
      end
    end

    def get_user_form_field_name(name)
      case name
      when :name                  then 'text_field'
      when :email                 then 'email_field'
      when :password              then 'password_field'
      when :password_confirmation then 'password_field'
      end
    end
end

backend/app/views/users/_edit_form.html.erb
<%= form_with model: @user, method: :patch do |f| %>
  <div class="space-y-6">
    <%= render 'shared/form_errors', object: f.object %>
    <%= settings_form_tag(f, :name, t('.name_description')) %>
    <%= settings_form_tag(f, :email) %>
    <%= settings_form_tag(f, :password) %>
    <%= settings_form_tag(f, :password_confirmation, t('.password_confirmation_description')) %>
    <%= settings_form_submit(f, t('.submit')) %>

    <%= user_form_destroy_field(f, t('.delete_user'), t('.delete_user_description')) %>
  </div>
<% end %>

backend/app/views/users/_new_form.html.erb
<%= form_with model: @user, method: :post do |f| %>
  <div class="space-y-4">
    <%= render 'shared/form_errors', object: f.object %>
    <%= recaptcha_v3 action: 'signup', turbolinks: true %>
    <%= user_form_field(f, :name, t('.name_description')) %>
    <%= user_form_field(f, :email) %>
    <%= user_form_field(f, :password) %>
    <%= user_form_field(f, :password_confirmation, t('.password_confirmation_description')) %>
    <%= user_form_submit(f, t('.submit')) %>
  </div>
<% end %>

backend/app/views/users/_select_form.html.erb
<%= form_with(url: users_path(), method: :get) do |f| %>
  <%= f.select(:sort, [
      [ t('.name'),  :name,   ],
      [ t('.email'), :email,  ],
      [ t('.new'),   :new,    ],
      [ t('.old'),   :old,    ],
    ], { include_blank: t('.sort') }, { onchange: 'this.form.submit()', class: 'block text-sm ml-auto p-2 border border-gray-200 bg-white rounded shadow focus:ring-amber-500 focus:border-amber-500' }) %>
<% end %>

backend/app/views/users/_user.html.erb
<%= content_tag(:div, id: dom_id(user), class: 'w-full p-4') do %>
  <div class="p-4 border border-gray-200 rounded shadow space-y-4">
    <div class="flex items-center overflow-scroll text-xs divide-x-2 bg-gray-100 rounded">
      <%= user_index_tag(user, :name) %>
      <%= user_index_tag(user, :email) %>

      <%= user_index_tag(user, :activated) %>
      <%= user_index_tag(user, :activated_at) %>

      <%= user_index_tag(user, :password_digest) %>
      <%= user_index_tag(user, :activation_digest) %>
      <%= user_index_tag(user, :reset_digest) %>

      <%= user_index_tag(user, :activation_sent_at) %>
      <%= user_index_tag(user, :reset_sent_at) %>

      <%= user_index_tag(user, :created_at) %>
      <%= user_index_tag(user, :updated_at) %>
    </div>
  </div>
<% end %>

backend/app/views/users/edit.html.erb
<% provide(:title, t('.title')) %>

<div class="block md:flex p-4 space-y-4 md:space-y-0 md:space-x-4">

  <%= render 'shared/settings_sidebar' %>

  <div class="md:basis-3/4 p-4 bg-amber-500 rounded shadow">
    <div class="text-left pl-4 pb-2 border-b border-gray-800 mb-4">
      <%= content_tag(:h1, yield(:title), class: 'text-xl') %>
    </div>
    <div class="text-sm">
      <%= render 'edit_form' %>
    </div>
  </div>
</div>

backend/app/views/users/followers.html.erb
<% provide(:title, t('.title', user: @user.name)) %>

<%= content_tag(:h1, t('.title', user: @user.name), class: 'text-xl text-left mt-2 ml-4 text-gray-800') %>

<%= render partial: 'users/user', collection: @user.followers %>

backend/app/views/users/following.html.erb
<% provide(:title, t('.title', user: @user.name)) %>

<%= content_tag(:h1, t('.title', user: @user.name), class: 'text-xl text-left mt-2 ml-4 text-gray-800') %>

<%= render partial: 'users/user', collection: @user.following %>

backend/app/views/users/index.html.erb
<% provide(:title, t('.title')) %>

<div class="p-4">
  <%= render 'select_form' %>
</div>

<div id="users">
  <%= render @users %>
</div>

backend/app/views/users/microposts.html.erb
<% provide(:title, t('.title')) %>

<%= content_tag(:h1, t('.title'), class: 'text-center text-xl p-2') %>

<%= render partial: 'microposts/micropost', collection: @user.microposts.order(created_at: :DESC) %>

backend/app/views/users/new.html.erb
<% provide(:title, t('.title')) %>

<div class="block lg:flex lg:signup-bg-img">
  <div class="lg:hidden">
    <%= image_tag 'signup.png' %>
  </div>
  <div class="w-full lg:max-w-lg text-sm">
    <div class="flex flex-col p-4 bg-white lg:bg-opacity-50 space-y-4">
      <div class="inline-block mx-auto bg-amber-300 border border-amber-500 rounded-full p-2">
        <%= site_logo(size: '64x64') %>
      </div>
      <div class="text-center text-xl pb-2 border-b border-gray-500 mb-4">
        <%= yield(:title) %>
      </div>
      <%= render 'new_form' %>

      <%= render 'providers/links' %>
    </div>
  </div>
<div>

backend/app/views/users/show.html.erb
<% provide(:title, t('.title')) %>

<div class="block md:grid md:grid-cols-6 p-4 space-y-2 md:space-y-0 md:space-x-2">
  <div class="col-span-2 text-sm p-2 border bg-white border-amber-500 shadow space-y-2 divide-y">
    <%= user_show_tag(@user.profile, :avatar,   class: '') %>
    <%= user_show_tag(@user.profile, :name,     class: '') %>
    <%= user_show_tag(@user,         :name,     class: '') %>
    <%= user_show_tag(@user.profile, :bio,      class: '') %>
    <%= user_show_tag(@user.profile, :location, class: '') %>
    <div class="flex items-center pt-2 space-x-4 border-amber-500">
      <%= fa_icon 'users' %>
      <div>
        <%= link_to(t('.followers'), user_followers_path(@user)) %>
        <span>|</span>
        <%= link_to(t('.following'), user_following_path(@user)) %>
      </div>
    </div>
    <div class="flex items-center pt-2 space-x-4 border-amber-500">
      <%= fa_icon 'handshake-o' %>
      <%= render 'relationships/page' if logged_in? %>
    </div>
  </div>

  <div class="col-span-4 p-2 border bg-white border-amber-500 shadow">
    <div class="text-center text-base">
      <%= link_to(t('.micropost_list'), user_microposts_path(@user)) %>
    </div>
    <%= render partial: 'microposts/micropost', collection: @user.microposts.take(4) %>
  </div>
</div>